version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: contract_parser_ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_CONTEXT_LENGTH=8192
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: contract_parser_backend
    environment:
      - OLLAMA_BASE_URL=http://192.168.3.63:11434
      # - OLLAMA_BASE_URL=http://ollama:11434
      # - OLLAMA_MODEL=qwen2.5:1.5b
      # - OLLAMA_MODEL=qwen3:30b-a3b-instruct-2507-q4_K_M
      # - OLLAMA_MODEL=qwen2.5vl:32b
      - OLLAMA_MODEL=qwen3:14b
      # - OLLAMA_MODEL=krith/qwen2.5-32b-instruct:IQ4_XS
      - SECTIONS_EXPORT_DIR=/exports
  
    depends_on:
      - ollama
    ports:
      - "8080:8000"
    volumes:
      - sections_data:/exports
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8080
    container_name: contract_parser_frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  ollama_data:
  sections_data: