version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: contract_parser_ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_CONTEXT_LENGTH=8192
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: contract_parser_backend
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=qwen2.5:1.5b
    depends_on:
      - ollama
    ports:
      - "8080:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8080
    container_name: contract_parser_frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  ollama_data: