version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: contract_parser_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: contract_parser_backend
    environment:
      - CONTRACT_PARSER_OLLAMA_BASE_URL=http://ollama:11434
      - CONTRACT_PARSER_SPECIFICATION_MODEL=llama3
      - CONTRACT_PARSER_CHAT_MODEL=llama3
    depends_on:
      - ollama
    ports:
      - "8080:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: contract_parser_frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  ollama_data: